name: Publish jsonify-ws to NPM

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Install root deps
        run: npm install

      - name: Build package
        run: |
          cd packages/jsonify-ws
          npm install
          npm run build
      - name: Version Patch
        run: |
          cd packages/jsonify-ws
          npm version patch
      - name: Publish package
        run: |
          cd packages/jsonify-ws
          npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
